### ISSUE TITLE
Plugin appends ~ to username

### ISSUE THREAD

**Issue by sitedyno** [hashworks/PhergieMessageSplitter#1]
RFC - Why does the plugin change the username?

https://github.com/hashworks/PhergieMessageSplitter/blob/98413e0c959d34a17b906f3bef5f6a5d4d5e7a2e/src/Plugin.php#L33

When using this plugin with PhergieKeepAlive the host mask changes like so after every reconnection:

```
botnick!botuser@bot.host
botnick!~botuser@bot.host
botnick!~~botuser@bot.host
botnick!~~~botuser@bot.host
```

**Comment by hashworks** [comment]
I need the username I get from the server so I can calculate the actual maximum string length.

However the multiple `~` look like a bug. I'll have a closer look at it tomorrow.

**Comment by hashworks** [comment]
Ok, it seems like the tilde as a seperator between nick and username is something that isn't RFC standard. I'll add a config switch for the servers that do. In that case I cut the tilde off before I save the username and change the calculation a bit.
